server:
    port: 8090


#public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==

#logging:
#  level:
#    learning: debug
#  config: classpath:logback-boot.xml

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    prefix: classpath:/templates
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  messages:
    basename: i18n/mess   ages
    encoding: utf-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  http:
    encoding:
      charset: UTF-8
#数据源配置
  datasource:
    url: jdbc:mysql://10.32.2.253:3306/cmvip
    username: root
    password: 123456
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.public-key}

#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==
    druid:
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: tp
        url-pattern: /druid/*
      filter:
        wall:
          db-type: mysql
          enabled: true
        stat:
          log-slow-sql: true
          db-type: mysql
          enabled: true
          slow-sql-millis: 200
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==
      initial-size: 0
      #定义最大连接数
      max-active: 1
      max-wait: 60000
  dubbo:
    application:
      name: log-consumer
      timeout: 8000
    registry:
      address: zookeeper://10.32.3.193:2181
      timeout: 100000
    scan: com.tp.api.controller



vip:
  uploadPath: /home/longxl/jar/upload/
