server:
    port: 8085


#public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==

#logging:
#  level:
#    learning: debug
#  config: classpath:logback-boot.xml

spring:
  dubbo:
    application:
      name: log-provider
      timeout: 8000
    registry:
      address: zookeeper://10.32.3.193:2181
      timeout: 100000
    protocol:
      name: dubbo
      port: 20888
      timeout: 8000
    scan: com.tp.api.service
    provider:
      timeout: 8000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    prefix: classpath:/templates
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  messages:
    basename: i18n/mess   ages
    encoding: utf-8
  #数据源配置
  datasource:
    url: jdbc:mysql://10.32.2.253:3306/cmvip
    username: root
    password: 123456
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.public-key}

#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==
    druid:
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: tp
        url-pattern: /druid/*
      filter:
        wall:
          db-type: mysql
          enabled: true
        stat:
          log-slow-sql: true
          db-type: mysql
          enabled: true
          slow-sql-millis: 200
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=200;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJJOxnCSrET2GzsYW3LB+GCo7yHTIeiii3qC7BlmjZwohXGA8hnTl1NwH9cgGwLvK8LnJ3tFe8cpBPvHq9VVKgsCAwEAAQ==
      initial-size: 1
      #定义最大连接数
      max-active: 50
      max-wait: 60000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  http:
    encoding:
      charset: UTF-8
  kafka:
    bootstrap-servers: 10.32.3.193:9092
    consumer:
      group-id: logcat
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer




## Dubbo 服务提供者配置
#spring.dubbo.application.name=provider
#spring.dubbo.registry.address=zookeeper://10.32.3.193:2181
#spring.dubbo.protocol.name=dubbo
#spring.dubbo.protocol.port=20880
#spring.dubbo.scan=com.jaycekon.dubbo.dbservice


#mybatis:
#  #实体类所做包
#  type-aliases-package: learning.model
#  #mapper.xml所在位置
#  mapper-locations: classpath:mappers/*.xml


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tp.api.entity
  typeEnumsPackage: com.tp.api.entity.enums

  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


vip:
  uploadPath: /home/longxl/jar/upload/
